// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hipsphwcywkicxjjqbjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcHNwaHdjeXdraWN4ampxYmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjM5MTgsImV4cCI6MjA3MDk5OTkxOH0.vJbilJR7rEBpw9JXwVOty-46GkkgLyIodGFNGKnNwrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});